### ISSUE TITLE
Associated cost with each action

### ISSUE THREAD

**Issue by SZanlongo** [leopepe/GOApy#4]
Since GOAP is using A* to find the best solution, is there a simple way of assigning a cost to each action? It might make sense in situations where a long chain of actions is still "cheaper" than a short sequence of very "expensive" actions.

**Comment by leopepe** [comment]
Yes. It is possible to add costs to the actions. The NetworkX framework supports it. I will include this on the TODO list. It is one thing that I had already discussed with some colleagues but forgot to plan this change.
If you have any intentions to contribute to the project I would be happy to merge your modifications. Please remember to create UnitTests if you do so.

**Comment by leopepe** [comment]
Added in version 0.2.1 (Yet to be tested)

PR: https://github.com/leopepe/GOApy/pull/15
